name: C++

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install required apt packages
      run: sudo apt-get install valgrind clang build-essential libssl-dev zlib1g-dev
    - name: install new version of cmake
      run: |
          curl -sSL https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.tar.gz -o cmake.tar.gz
          sudo tar xf cmake.tar.gz --strip 1 -C /usr/local
    - name: configure
      run: cmake .
    - name: build
      run: cmake --build . --target Net
    - name: test with memory check
      run: cd test &&valgrind --tool=memcheck  --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no --error-exitcode=1 ./Catch_tests_run -d yes
